# ===== INPUT SETTINGS ==== 

input:
    input_folder: '/primary/data/common/VDKN/OwnAmplicons_RAW/2026-12-05_allele_specific_v2_merged_lanes' # input folder with raw fastq files 
    include_patterns: []  # list of patterns or sample names to include, e.g. ['CYP21A2', 'SEQ[1,6]']. if empty, all are included 
    exclude_patterns: [] # list of patterns or sample names to exclude, e.g. ['SAMPLE_1', 'SEQ[2,7]']
    fastq_extensions: ['fastq.gz', 'fq.gz']
    ped_file: # OPTIONAL ped file that will be used for relatedness phasing. If none, only read-based phasing is done  /primary/data/zantysheva/projects/vdkn/mlpa_cohort_ped.tsv

# ===== OUTPUT SETTINGS ====         
output:
    output_folder: '/primary/data/common/VDKN/paper_diagnostics_amps/allele_specific_amps_v2'
    save_all_callers: True
    # True or False; this flag is used to mark if all callers outputs should be preserved, or only conflict resolved output should be saved 

# ===== REFERENCE SETTINGS ====  

references: 
    amplicon: '/primary/data/zantysheva/git_clones/AmpliconPipe/reference/CYP21A2/CYP21A2-amp_hg38.fasta' # Amplicon fasta .fasta
    amplicon_bed: '/primary/data/zantysheva/git_clones/AmpliconPipe/reference/CYP21A2/CYP21A2.bed' # bed file for calling interval. Can be the all amplicon span
    pseudogene_coordinates: 'chr6:32005689-32008399' # OPTIONAL. If the amplicon has highly homological sequence in genome (>=90%) e.g. CYP21A1P for CYP21A2, CYP2D7 for CYP2D6, SMN2 for SMN1, coordinates can be given to check contamination from this region specifically. Better performance is achieved if coordinates for homological region include all the length of homological region in amplicon, not only gene or pseudogene. Adding extra ~1000 b.p on sides also can help 
    full_genome: '/primary/data/zantysheva/data/reference/Homo_sapiens_assembly38/Homo_sapiens_assembly38.fasta' # OPTIONAL. full reference sequence of the organism. Required only if pseudogene coordinates are given 


# ===== EXECUTION PARAMS ===== 
    
run_settings:
    engine: 'singularity' # singularity OR docker 

user_settings:
    # your group (or other group id) so that final files in docker will be saved from your user, not as root user 
    # get the number with "id -g" in terminal 
    GID: 2009 

# ===== DEFAULT TASK RESOURCES =====
# ===== do not change if you do not know what you are doing =====

# memory and cpus for each of the rules
rules_settings:
    fastq2bam: 
        runtime: 200
        mem_mb: 4000
        cpus_per_task: 15
        
    HaplotypeCaller: 
        runtime: 200
        mem_mb: 4000
        cpus_per_task: 15
        
    mosdepth:
        runtime: 200
        mem_mb: 4000
        cpus_per_task: 4
        
    mpileup:
        runtime: 200
        mem_mb: 4000
        cpus_per_task: 15
        
    DeepVariant: 
        runtime: 400
        mem_mb: 4000
        cpus_per_task: 15
    
    resolve_conflicts:
        runtime: 100
        mem_mb: 500
        cpus_per_task: 2

    whatshap:
        runtime: 1200
        mem_mb: 7000
        cpus_per_task: 10

    PloidyContaminationQC:
        runtime: 100
        mem_mb: 500
        cpus_per_task: 2

    index_reference:
        runtime: 200
        mem_mb: 1000
        cpus_per_task: 2 

    gatk_dict:
        runtime: 200
        mem_mb: 1000
        cpus_per_task: 2 

    pseudogenic_synth_reads:
        runtime: 200
        mem_mb: 2000
        cpus_per_task: 10

    generate_pseudo_synth_bam:
        runtime: 200
        mem_mb: 2000
        cpus_per_task: 10

    call_variants_different_in_gene:
        runtime: 200
        mem_mb: 2000
        cpus_per_task: 10

    HaplotypeCallerAltPloidy:
        runtime: 500
        mem_mb: 6000
        cpus_per_task: 15

    quality_checked_AltPloidy:
        runtime: 100
        mem_mb: 500
        cpus_per_task: 2

    whatshap_polyphase:
        # high coverages (~3000X) result in very long polyphase runtimes 
        runtime: 48000 
        mem_mb: 15000
        cpus_per_task: 8

    relatedness_phasing:
        runtime: 100
        mem_mb: 500
        cpus_per_task: 2

    multiqc: 
        runtime: 200
        mem_mb: 500
        cpus_per_task: 2
